url: "http://ocmock.org"
highlighter: pygments
exclude: [bin, Gemfile, Gemfile.lock, Makefile]
permalink: pretty
paginate: 50
paginate_path: "news/page:num"
date_format: "%d %B %Y"
baseurl: "http://ocmock.org"
